### ISSUE TITLE
How to train with folder video

### ISSUE THREAD

**Issue by Splendon** [ExponentialML/Text-To-Video-Finetuning#102]
Hello, thanks a lot for this project.
I would like to finetune train with folder video，but I cannot find some train config examples of the videos folder with the related prompt json，such as the following:
-----------------------------------------------------------------------------------------------
  # 'folder'
  path: "path/to/folder/of/videos/"
  # 'json'
  json_path: 'path/to/train/json/'
-------------------------------------------------------------------------------------------------
Is there any train config examples about the json_path and the json format, thanks

**Comment by JCBrouwer** [comment]
The json format that's expected is the one generated by this repo: https://github.com/ExponentialML/Video-BLIP2-Preprocessor

It's basically just a list with video file paths and then a dict per video with captions per timestamp.

I don't have an example at the moment, but if you don't have video captions yet you can generate them with that repo.

I think at some point you could also just put captions in a .txt with the same name as the .mp4 but I'm not sure if that's still in the newest version / how you would configure that...
