### ISSUE TITLE
 RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1, 512] because the unspecified dimension size -1 can be any value and is ambiguous 

### ISSUE THREAD

**Issue by Splendon** [ExponentialML/Text-To-Video-Finetuning#104]
When I run finetune training with json，I meet this error.
The training json dataset is gotten from running preprocess.py of this repo, https://github.com/ExponentialML/Video-BLIP2-Preprocessor

**Comment by ExponentialML** [comment]
Hey. Can you verify that the directories to the videos are correct?

**Comment by Splendon** [comment]
Yes，I use the json made from  https://github.com/ExponentialML/Video-BLIP2-Preprocessor for training.
Some data can be dealed during, but after dealed some data, it meet this error.

**Comment by Splendon** [comment]
It is possible my training dataset owns some error mp4.
