### ISSUE TITLE
wrong norm method

### ISSUE THREAD

**Issue by BooHwang** [ExponentialML/Text-To-Video-Finetuning#135]
https://github.com/ExponentialML/Text-To-Video-Finetuning/blob/83e11c702b2fb30248e488bc0a11680cfaa56558/utils/dataset.py#L41

maybe it should be:

return rearrange(item / 127.5 - 1.0), 'f h w c -> f c h w')

**Comment by ExponentialML** [comment]
Resolved here: https://github.com/ExponentialML/Text-To-Video-Finetuning/pull/133
