### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by suzhenghang** [ExponentialML/Text-To-Video-Finetuning#14]
will it be difficult to modify the code to support multi-gpu training?

**Comment by ExponentialML** [comment]
> will it be difficult to modify the code to support multi-gpu training?

I've never tried multiple GPU training, but you may be able to do it naively with accelerate.

`accelerate config`

You should be prompted to configure your setup, including multiple GPU training.
Then it should be as simple as:

`accelerate launch train.py --config ./configs/my_config_hq.yaml`

Let us know how it goes if you decide to try! If it doesn't I could try to implement it, but I don't have multiple GPUs and would probably need to rent out a server to do so.

**Comment by suzhenghang** [comment]
Yes，as your suggestion above, i can use the distributed training and the generation is as good as one GPU

**Comment by ImBadAtNames2019** [comment]
> Yes，as your suggestion above, i can use the distributed training and the generation is as good as one GPU

What do you mean with "as good as one gpu"? You mean, if you had a single gpu as powerful as both of the gpus that you are using combined, there would be no difference? Also, are you connecting them through nvlink, or its just pcie?
