### ISSUE TITLE
Custom resolution?

### ISSUE THREAD

**Issue by adhikjoshi** [ExponentialML/Text-To-Video-Finetuning#18]
Is there possibility of having custom resolution for training/inference ?

**Comment by ExponentialML** [comment]
@adhikjoshi Yes you can do both, albeit it gets computationally heavy as you get closer to 512x512.

Typically in my tests, 384x256 for widescreen seems to work well for both training and inference seem to work well. For training, it's a must to keep the frames low (< 4) or else it won't fit into memory. 

There *may* be some duplication problems as the model was trained on videos at a 1:1 ratio to the best of my knowledge.

**Comment by Askejm** [comment]
check width and height in the example yamls in the config folder

**Comment by sergiobr** [comment]
I was wondering if it would be successful to train on resolution like 512x256 for stereoscopic videos?
