### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by eliohead** [ExponentialML/Text-To-Video-Finetuning#20]
I am a lazy person. 
Has anyone managed to run the finetune on Colab?

**Comment by patrickjonesdotca** [comment]
The other problem I ran into was it not installing the models correctly in the proper directory because each command seems to run from root and not from last known location:

```
!git clone https://github.com/ExponentialML/Text-To-Video-Finetuning.git
!cd Text-To-Video-Finetuning
!git lfs install
!git clone https://huggingface.co/damo-vilab/text-to-video-ms-1.7b ./models/model_scope_diffusers/
```

Which means the process just hangs

**Comment by patrickjonesdotca** [comment]
Still looking. Not sure why git is hanging but can replicate the issue both on Colab and on my laptop

**Comment by patrickjonesdotca** [comment]
Turns out the problem was just me. It takes a while and without any progressbar it seems to hang but it still working.
Continuing on.

**Comment by patrickjonesdotca** [comment]
Update: ran into the same issue here: https://github.com/ExponentialML/Text-To-Video-Finetuning/issues/61 and suspected my process missed something. Going to regen another fine-tune and update when I can

**Comment by charuj** [comment]
@patrickjonesdotca would you be able to share your colab notebook? I'm trying to get this to run in Colab as well and am running into the same issues mentioned above with install & inference 
Thanks in advance!

**Comment by charuj** [comment]
The following ensures the install happens in the right place (i.e. this is how to get the location to persist when doing cd in Google Colab):

```
!git clone https://github.com/ExponentialML/Text-To-Video-Finetuning.git
%cd Text-To-Video-Finetuning
!git lfs install
!git clone https://huggingface.co/damo-vilab/text-to-video-ms-1.7b ./models/model_scope_diffusers/
```

**Comment by patrickjonesdotca** [comment]
> The following ensures the install happens in the right place (i.e. this is how to get the location to persist when doing cd in Google Colab):
> 
> ```
> !git clone https://github.com/ExponentialML/Text-To-Video-Finetuning.git
> %cd Text-To-Video-Finetuning
> !git lfs install
> !git clone https://huggingface.co/damo-vilab/text-to-video-ms-1.7b ./models/model_scope_diffusers/
> ```
> 
> notice the %cd ...

Thank you!

**Comment by zacaikido** [comment]
Hey, when trying 
`!python train.py --config /path/to/Text-To-Video-Finetuning/configs/v2/low_vram_config_example.yaml`

get  :  
`Traceback (most recent call last):
  File "/content/drive/MyDrive/Text-To-Video-Finetuning/train.py", line 998, in <module>
    main(**OmegaConf.load(args.config))
  File "/content/drive/MyDrive/Text-To-Video-Finetuning/train.py", line 577, in main
    accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'`

Any idea ?

**Comment by ExponentialML** [comment]
There is a finetuning Colab here: https://github.com/camenduru/Text-To-Video-Finetuning-colab

Please let me know if there are any issues, and I'll re-open.
