### ISSUE TITLE
Using a trained model on webui

### ISSUE THREAD

**Issue by bruefire** [ExponentialML/Text-To-Video-Finetuning#29]
Is it possible?
Is there information that I should refer to anywhere?

**Comment by ExponentialML** [comment]
> 

Hey! It should be doable as there just needs to be a conversion script similar to the ones we have now. 
I''ll look into creating one if I get around to it (if one isn't created already).

**Comment by suzhenghang** [comment]
@ExponentialML  Do you have plans to support a web UI in the near future?

**Comment by ExponentialML** [comment]
> @ExponentialML Do you have plans to support a web UI in the near future?

Yes I do!
