### ISSUE TITLE
The video dosent move.

### ISSUE THREAD

**Issue by ImBadAtNames2019** [ExponentialML/Text-To-Video-Finetuning#31]
After finetuning, the output video dosent move, it just stays still. It looks good but there is no movement.

**Comment by ImBadAtNames2019** [comment]
I trained it on a single video, maybe thats the problem?

**Comment by dvschultz** [comment]
I found if I overtrain the model it can lead to this. Try and earlier checkpoint and see if that is an improvement. It might also be, as you mention, the effect of a single video.

Also make sure you set `n_sample_frames` as high your hardware will allow.
