### ISSUE TITLE
Is this the new version of the model?

### ISSUE THREAD

**Issue by ImBadAtNames2019** [ExponentialML/Text-To-Video-Finetuning#36]
There was a new version of modelscope released recently, it was trained for a month longer and it can generate better videos, is this repo using the new model or the old one?

**Comment by ImBadAtNames2019** [comment]
Also, do you know that a new 6 billion parameters version of modelscope will be released soon, do you think this repo will work with it? That would be incredible. Heres the link https://www.modelscope.cn/models/damo/cv_diffusion_text-to-video-synthesis/summary

**Comment by ExponentialML** [comment]
This repository uses the 1.7 billion parameter model. If they decide to upload it to huggingface as a diffusers pipeline, it will most definitely be integrated here.
