### ISSUE TITLE
Does using "attentions" unfreeze all the layers?

### ISSUE THREAD

**Issue by ImBadAtNames2019** [ExponentialML/Text-To-Video-Finetuning#37]
Also, what layers should i unfreeze the get the best possible quality? Even if it consumes a ton of vram.

**Comment by ExponentialML** [comment]
Attentions only unfreeze the attention layers. Here is a list of all the layers in the model: https://gist.github.com/ExponentialML/b642fd66245603fc04679888fe890f2f

If you have a ton of VRAM, optimally you would want to unfreeze *all* the layers. The attention / convolution layers are usually the ones you need to tune in most cases though.

**Comment by ImBadAtNames2019** [comment]
> Attentions only unfreeze the attention layers. Here is a list of all the layers in the model: https://gist.github.com/ExponentialML/b642fd66245603fc04679888fe890f2f
> 
> If you have a ton of VRAM, optimally you would want to unfreeze _all_ the layers. The attention / convolution layers are usually the ones you need to tune in most cases though.

So "attentions" unfreezes all the attention layers, what about the convolution layers? Do i use "convolutions" to unfreeze all of them?

**Comment by ImBadAtNames2019** [comment]
Is this right? Does this unfreeze all the attention and convolution layers?:

trainable_modules:
  - "attentions"
  - "conv1"
  - "conv2"
  - "conv3"
  - "conv4"

**Comment by ImBadAtNames2019** [comment]
> The unfreezing code searches through all of the parameter keys (in the gist up above) and will enable any that match the substrings in the config.
> 
> trainable_modules:
> 
> * "attentions"
> * "convs"
> 
> will enable the vast majority of parameters in the model

Ahh i get it now, thanks.
