### ISSUE TITLE
Is there a problem with attn3 here?

### ISSUE THREAD

**Issue by suzhenghang** [ExponentialML/Text-To-Video-Finetuning#40]
[code](https://github.com/ExponentialML/Text-To-Video-Finetuning/blob/main/configs/video_folder.yaml#L32)，from the [network of unet3d](https://gist.github.com/ExponentialML/b642fd66245603fc04679888fe890f2f), attn3 will do nothing?

**Comment by JCBrouwer** [comment]
Yep, that's my bad 'attn3' doesn't exist and does nothing when added to the config
