### ISSUE TITLE
How does  n_sample_frames: work?

### ISSUE THREAD

**Issue by ImBadAtNames2019** [ExponentialML/Text-To-Video-Finetuning#42]
So for example, if i have set it to 4, it will finetune using only 4 frames of the video, no matter the length of the video?

**Comment by JCBrouwer** [comment]
Yes, it'll sample `n_sample_frames` frames at a rate of `fps` from a random moment in the video.

You can find the code here: https://github.com/ExponentialML/Text-To-Video-Finetuning/blob/25697f97af78161ce7f57fbbe6dbab186b0f0bff/utils/dataset.py#L239
