### ISSUE TITLE
Whats the deal with train_text_encoder: ?

### ISSUE THREAD

**Issue by ImBadAtNames2019** [ExponentialML/Text-To-Video-Finetuning#43]
Should i train it or not? I tested it and i didnt see any difference, is it better to just keep it on all the time?

**Comment by ImBadAtNames2019** [comment]
Actually i was wrong, training the text encoder makes the output look much worse, isnt it supposed to make things better?

**Comment by ExponentialML** [comment]
> Should i train it or not? I tested it and i didnt see any difference, is it better to just keep it on all the time?

It makes a very big difference but requires a lot of VRAM. It will be available in version 2.
