### ISSUE TITLE
Encountered 2 file(s) that may not have been copied correctly on Windows

### ISSUE THREAD

**Issue by one-shot-finish** [ExponentialML/Text-To-Video-Finetuning#60]
I see the following after `Requirements and Installation` step

```
Encountered 2 file(s) that may not have been copied correctly on Windows:
	unet/diffusion_pytorch_model.safetensors
	unet/diffusion_pytorch_model.bin
```

Could this break something during finetuning ?

**Comment by ExponentialML** [comment]
Yes it will You could try going to the following link and downloading them directly.

https://huggingface.co/damo-vilab/text-to-video-ms-1.7b/tree/main
