### ISSUE TITLE
TypeError: get_logger() got an unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by Devalinor** [ExponentialML/Text-To-Video-Finetuning#7]
Hi, I am trying to run your script but it always shows me this error.
Another thing is that it's not possible for me to install triton. It's like the repo doesn't exist anymore.
```
Error caught was: No module named 'triton'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Life\Text-To-Video-Finetuning\train.py:43 in <module>                                   │
│                                                                                                  │
│    40 # Will error if the minimal version of diffusers is not installed. Remove at your own ri   │
│    41 check_min_version("0.10.0.dev0")                                                           │
│    42                                                                                            │
│ ❱  43 logger = get_logger(__name__, log_level="INFO")                                            │
│    44                                                                                            │
│    45 def create_logging(logging, logger, accelerator):                                          │
│    46 │   logging.basicConfig(                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: get_logger() got an unexpected keyword argument 'log_level'
```

**Comment by ExponentialML** [comment]
> Hi, I am trying to run your script but it always shows me this error. Another thing is that it's not possible for me to install triton. It's like the repo doesn't exist anymore.
> 
> ```
> Error caught was: No module named 'triton'
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ C:\Users\Life\Text-To-Video-Finetuning\train.py:43 in <module>                                   │
> │                                                                                                  │
> │    40 # Will error if the minimal version of diffusers is not installed. Remove at your own ri   │
> │    41 check_min_version("0.10.0.dev0")                                                           │
> │    42                                                                                            │
> │ ❱  43 logger = get_logger(__name__, log_level="INFO")                                            │
> │    44                                                                                            │
> │    45 def create_logging(logging, logger, accelerator):                                          │
> │    46 │   logging.basicConfig(                                                                   │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> TypeError: get_logger() got an unexpected keyword argument 'log_level'
> ```

Can you try `pip install accelerator -U ` and see if that solves the issue?
Also on your issue about Triton, `pip install triton` seems to work for me. Which version of Python are you running?

**Comment by ExponentialML** [comment]
@Devalinor You need to go here and download the files. 

https://huggingface.co/damo-vilab/text-to-video-ms-1.7b/tree/main.

1. Place them in a folder `./some_directory/modelscope`
2. The folder structure must be the same as above.

You can also try this in the command line, but you may get all of the mode files. Then you can point to the directory it was downloaded to in your config.

```
git lfs install
git clone https://huggingface.co/damo-vilab/text-to-video-ms-1.7b
```

**Comment by JPW0080** [comment]
Also, Triton on Win:
pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by seel-channel** [comment]
> Also, Triton on Win: pip install https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl

![image](https://user-images.githubusercontent.com/65832922/227836862-5ca0ef57-5f1d-49f1-9917-3bf2eb0defa2.png)
