### ISSUE TITLE
How much VRAM do I need for saving the weights?

### ISSUE THREAD

**Issue by Darkbblue** [ExponentialML/Text-To-Video-Finetuning#72]
I have 16GB available at first place. <12GB is used for training. Then I encounter OOM when saving the weights. This feels a bit insane...

**Comment by Darkbblue** [comment]
I guess it has something to do with the deepcopy before saving the model. The model itself seems to occupy ~10GB so copying it requires ~20GB in total?

**Comment by kabachuha** [comment]
@cerspense @camenduru

**Comment by Darkbblue** [comment]
Guys I delete the deepcopy and now I can save the weights without too much additional VRAM. The only problem is that this may disallow me to continue training after saving.
```python
   # Copy the model without creating a reference to it. This allows keeping the state of our lora training if enabled.
    # unet_out = copy.deepcopy(accelerator.unwrap_model(unet, keep_fp32_wrapper=False))
    # text_encoder_out = copy.deepcopy(accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=False))
    unet_out = (accelerator.unwrap_model(unet, keep_fp32_wrapper=False))
    text_encoder_out = (accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=False))
```

**Comment by ExponentialML** [comment]
Should be fixed now. Let me know if it's still an issue.
