### ISSUE TITLE
Refer to the official release of Diffusers?

### ISSUE THREAD

**Issue by tin2tin** [ExponentialML/Text-To-Video-Finetuning#77]
It seems like the models finetuned for Diffusers are referring to the latest beta version and not the latest official release of Diffusers, making the models error out when trying to load them with the official version of Diffusers. Could it be change to official releases referred to instead?

**Comment by ExponentialML** [comment]
> It seems like the models finetuned for Diffusers are referring to the latest beta version and not the latest official release of Diffusers, making the models error out when trying to load them with the official version of Diffusers. Could it be change to official releases referred to instead?

Yes, this will be one of the major things to be done. It might involve a bit more testing as the early release (the one this branch is based on) will be a bit different from the official releases.

**Comment by ExponentialML** [comment]
Should be solved via this commit: https://github.com/ExponentialML/Text-To-Video-Finetuning/commit/89221af707bf57dfba6fc5918c2f62d0886d4aa8 .
