### ISSUE TITLE
error of "from accelerate.logging import get_logger"

### ISSUE THREAD

**Issue by Splendon** [ExponentialML/Text-To-Video-Finetuning#98]
Hi, I meet the following error when I run finetune training.
(aigc) cwh8szh@SZH-C-006RW:/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning$ CUDA_VISIBLE_DEVICES=1 python train.py --config ./configs/v2/train_config_caixukun.yaml
Traceback (most recent call last):
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 1035, in <module>
    main(**OmegaConf.load(args.config))
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 617, in main
    create_logging(logging, logger, accelerator)
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 64, in create_logging
    logger.info(accelerator.state, main_process_only=False)
AttributeError: 'str' object has no attribute 'info'

I have tried different version of accelerate, but cannot slove this error.
the following of my main pip list:
Package                  Version
------------------------ -----------
accelerate               0.20.3
tensorboard              2.10.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tokenizers               0.13.3
torch                    2.0.1
torchaudio               2.0.2
torchvision              0.15.2
transformers             4.30.2
triton                   2.0.0

**Comment by ExponentialML** [comment]
Hello. I fixed this error yesterday. Please update and also reinstall your requirements.

**Comment by Splendon** [comment]
Thanks, Done.
