### ISSUE TITLE
finetune train error of "UnboundLocalError: local variable 'use_offset_noise' referenced before assignment"

### ISSUE THREAD

**Issue by Splendon** [ExponentialML/Text-To-Video-Finetuning#99]
after I comment the code about get_logger, I can run as the following output, but meet the other error.
————————————————————————————————————————————
(aigc) cwh8szh@SZH-C-006RW:/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning$ CUDA_VISIBLE_DEVICES=1 python train.py --config ./configs/v2/train_config_caixukun.yaml
{'variance_type', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
{'downsample_padding', 'mid_block_scale_factor'} was not found in config. Values will be initialized to default values.
33 Attention layers using Scaled Dot Product Attention.
LoRA rank 16 is too large. setting to: 4
LoRA rank 16 is too large. setting to: 4
Lora successfully injected into UNet3DConditionModel.
Lora successfully injected into CLIPTextModel.
Non-existant JSON path. Skipping.
Caching Latents.: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:14<00:00,  2.68it/s]
Steps:   0%|                                                                                                                                                           | 0/10000 [00:00<?, ?it/s]2628 params have been unfrozen for training.
Traceback (most recent call last):
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 1035, in <module>
    main(**OmegaConf.load(args.config))
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 908, in main
    loss, latents = finetune_unet(batch, train_encoder=train_text_encoder)
  File "/mnt/workspace/cwh8szh/aigc/Text-To-Video-Finetuning/train.py", line 810, in finetune_unet
    use_offset_noise = use_offset_noise and not rescale_schedule
UnboundLocalError: local variable 'use_offset_noise' referenced before assignment
Steps:   0%|                                                                                                                                                           | 0/10000 [00:55<?, ?it/s]
————————————————————————————————————————————
Is there more guideline of finetune training, much thanks.

**Comment by ExponentialML** [comment]
https://github.com/ExponentialML/Text-To-Video-Finetuning/issues/98#issuecomment-1633063349

**Comment by Splendon** [comment]
Done
